/* Real model adapter. Never silently falls back to canned replies. */
/* 线上部署 2026-10-07：GitHub Pages 时走 Cloudflare Worker 中转；本地开发仍用本机服务。 */
const API_BASE=(['127.0.0.1','localhost'].includes(location.hostname))?'':(window.MYSELF_API_BASE||'');
let aiBusy=false,aiRetry=null,aiStatus=null;
const beforeAiAgent=agent;
agent=function(){let html=beforeAiAgent().replace('本地对话演示 · 尚未接入大模型 API',aiStatus?.ready?'DeepSeek 已连接 · 确认后才会更新计划':esc(aiStatus?.message||'正在检查模型连接…'));if(aiBusy)html=html.replace('<div class="agent-tools">','<div class="ai-wait" role="status">'+(flow().mode==='generating'?'正在帮你整理「'+esc(flow().data?.title||'这次目标')+'」的安排，马上好…':'Agent 正在听你说，也在认真整理…')+'</div><div class="agent-tools">');if(aiRetry)html=html.replace('<div class="agent-tools">',btn('重试上一条消息','aiRetry','ai-retry')+'<div class="agent-tools">');return html};
const localStages=planStages;planStages=function(d){return Array.isArray(d.stages)?d.stages:localStages(d)};
newDraft=function(){state.agentFlow={mode:'chat',data:{}};chatContext=null;state.aiTopicStart=state.messages.length;say('好呀，这次有什么想做的事？先说说你的想法就行。');go('agent');refreshChat(true)};
async function requestAi(mode){const contextStart=state.aiContextStart||0;const current=flow();const context={mode,today:M.day(),messages:state.messages.slice(Math.max(state.aiContextStart||0,state.aiTopicStart||0)).slice(-24),memories:state.memories,summary:{slots:M.slots(state),cards:state.cards,cancelRemaining:qleft('cancel'),undoRemaining:qleft('undo')},goals:[...state.goals.filter(g=>['active','paused'].includes(g.status)),...state.goals.filter(g=>!['active','paused'].includes(g.status)).slice(-10)],draft:{mode:current.mode,data:current.data,goalId:chatContext}};if(!['127.0.0.1','localhost'].includes(location.hostname)&&!API_BASE)throw new Error('线上服务尚未配置完成，请稍后再试。');const response=await fetch(API_BASE+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(context),signal:AbortSignal.timeout(105000)});const result=await response.json();if((state.aiContextStart||0)!==contextStart)throw new Error('记忆上下文已更新，请重新发送。');if(!response.ok)throw new Error(result.error||'连接失败，请重试。');track('ai_response',{model:result.meta?.model,durationMs:result.meta?.durationMs,tokens:result.meta?.tokens,kind:result.action});return result}
async function realTurn(mode='chat'){if(aiBusy)return;aiBusy=true;aiRetry=null;refreshChat();const turnEpoch=state.aiContextStart||0;const before=JSON.parse(JSON.stringify(flow()));try{let r=await requestAi(mode);if(r.memoryOps?.length){const latest=state.messages.filter(m=>m.role==='user').at(-1)?.text||'';if(!transact('memorySync',{ops:r.memoryOps,userText:latest}))throw new Error('记忆保存失败，请重试。');}Object.assign(flow().data,r.facts||{});if(r.action==='ready'){flow().mode='generating';say('好，这就帮你整理「'+esc(flow().data?.title||'这次目标')+'」的安排…');refreshChat();mode='generate';r=await requestAi('generate')}
if(mode==='generate'&&r.action!=='plan'&&r.action!=='chat')throw new Error('计划尚未生成成功，请重试。');
if(r.action==='plan'){state.agentFlow={mode:'review',data:r.plan,draftId:M.id()};say('我已经整理好啦，你觉得这样如何？有要修改的地方可以和我说哦。')}
else if(r.action==='memory'){state.agentFlow={mode:'chat',data:{}};say('已处理这次记忆删除；旧聊天不会再用于后续回复，正式计划与完成记录不受影响。')}
else if(r.action==='discard'){state.agentFlow={mode:'chat',data:{}};say(r.reply)}
else if(r.action==='adjust'){state.agentFlow={mode:'chat',data:{}};say('本版本暂未开放正式计划调整。你可以和我说说遇到的变化，我们先一起讨论，现有任务不会被修改。')}
else{if(flow().mode==='generating')flow().mode='chat';say(r.reply)}save()}
catch(e){state.agentFlow=(state.aiContextStart||0)===turnEpoch?before:{mode:'chat',data:{}};aiRetry=mode;say(mode==='generate'?'当前好像出了点小状况，你提供的信息已保留，点下方「重试上一条消息」再试一次。':'当前好像出了点小状况，点下方「重试上一条消息」再试一次。');track('ai_error',{reason:'request_failed',detail:e.message})}
finally{aiBusy=false;if(route==='agent')refreshChat()}}
chatSend=async function(text){if(aiBusy)return toast('请等 Agent 回复后再发送。');text=text.trim();if(!text)return;if(offline||!navigator.onLine)return toast('当前离线，消息未发送。');if(/^记住[:：]/.test(text)){legacyChatSend(text);return}const input=document.querySelector('#chat-input');if(input)input.value='';state.messages.push({role:'user',text:text.slice(0,1500)});save();await realTurn()};
// Editing a draft stays a conversation, with the previous complete draft available as context.
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='aiRetry'&&aiRetry)realTurn(aiRetry);if(a==='editPlanReview'||a==='agentEdit'){flow().mode='chat';flow().pending=null;save()}},false);
const priorAdjustCard=conversationCard;conversationCard=function(){let html=priorAdjustCard();const f=flow();if(f.mode==='adjust'&&f.proposedDate)html=html.replace(/name="date" type="date" value="[^"]*"/,'name="date" type="date" value="'+esc(f.proposedDate)+'"');return html};
// Prevent goal switching/new requests while an answer is in flight.
document.addEventListener('click',e=>{if(!aiBusy)return;const a=e.target.closest('[data-action]')?.dataset.action;if(['newGoal','agentCasual','agentDiscard','context','setContext','editPlanReview','agentEdit'].includes(a)){e.preventDefault();e.stopImmediatePropagation();toast('请等当前回复完成。')}},true);
fetch(API_BASE?API_BASE+'/health':'/api/status').then(r=>r.json()).then(s=>{aiStatus=API_BASE?{ready:!!s.ok}:s;if(route==='agent')refreshChat(false)}).catch(()=>{aiStatus={ready:false,message:API_BASE?'线上服务暂时没连上，发消息可能会失败，稍后再进来试试。':'请双击“启动原型.cmd”启动 API 版本。'};if(route==='agent')refreshChat(false)});
render();

