const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),initialApi=require('./deepseek-service.cjs');
let api=initialApi,serviceStamp='';function refreshService(){const stamp=['deepseek-service.cjs','agent-rules.js'].map(f=>fs.statSync(path.join(__dirname,f)).mtimeMs).join(':');if(stamp!==serviceStamp){for(const f of ['./deepseek-service.cjs','./agent-rules.js'])delete require.cache[require.resolve(f)];api=require('./deepseek-service.cjs');serviceStamp=stamp;}}
const root=__dirname,port=Number(process.env.PORT||4213),origin='http://127.0.0.1:'+port;let busy=false;
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))};
http.createServer(async(req,res)=>{if(!['127.0.0.1:'+port,'localhost:'+port].includes(req.headers.host)){res.writeHead(403);return res.end()}
if(req.url==='/__version')return res.end('Myself-0.3-api-r4');
if(req.url==='/api/status'){try{refreshService();const c=await api.credentials();return json(res,200,{ready:true,model:c.model})}catch(e){return json(res,200,{ready:false,message:e.message})}}
if(req.url==='/api/chat'){if(req.method!=='POST'||![origin,'http://localhost:'+port].includes(req.headers.origin))return json(res,403,{error:'请求来源无效。'});if(busy)return json(res,429,{error:'上一条消息仍在回复中。'});let body='';try{for await(const part of req){body+=part;if(Buffer.byteLength(body)>100000)return json(res,413,{error:'对话内容过长。'})}const input=JSON.parse(body);busy=true;refreshService();const output=await api.chat(input);return json(res,200,output)}catch(e){return json(res,e.status||500,{error:e instanceof api.ApiError?e.message:'请求处理失败，请重试。',code:e.code||'INTERNAL'})}finally{busy=false}}
let p;try{p=decodeURIComponent(new URL(req.url,origin).pathname)}catch{return json(res,400,{error:'无效路径'})}const f=path.resolve(root,'.'+(p==='/'?'/index.html':p));if(!f.startsWith(root+path.sep)||!['.html','.js','.css','.png','.webp','.webmanifest','.ico'].includes(path.extname(f))||/test/i.test(path.basename(f))){res.writeHead(404);return res.end()}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp','.webmanifest':'application/manifest+json','.ico':'image/x-icon'})[path.extname(f)],'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});res.end(b)})}).listen(port,'127.0.0.1',()=>console.log('Myself API ready on '+port));
