const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));const click=async(a)=>page.locator(`[data-action="${a}"]`).first().click();const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('myself-p0-v1')));const report=[];await page.goto('http://localhost:4173');await page.screenshot({path:'preview-mobile.png'});
await click('homeStart');await click('pauseTask');await click('startTask');await click('completeTask');let s=await read();assert.equal(s.coins,500);assert.equal(s.xp,400);await page.reload();s=await read();assert.equal(s.goals[0].tasks[0].state,'done');report.push('开始、暂停、继续、完成，刷新后保留记录');
await click('exchange');await click('confirmModal');s=await read();assert.equal(s.coins,0);assert.equal(s.cards,3);report.push('兑换扣500金币、增加1张卡，背包联动');
await click('newGoal');await page.locator('[name="title"]').fill('学习英语');await page.locator('#draft-form button[type="submit"]').click();await click('draftGenerate');await page.locator('[name="action"]').fill('学习5个单词');await page.locator('#plan-edit button[type="submit"]').click();await click('create');s=await read();assert.equal(s.goals.length,2);assert.equal(s.cards,2);const created=s.goals[1];report.push('目标澄清、摘要确认、修改方案与扣卡创建');
await click('adjustGoal');await page.locator('[name="title"]').fill('学习3个单词并复习');await page.locator('#adjust-form button[type="submit"]').click();await click('confirmModal');s=await read();assert.equal(s.goals[1].tasks[0].title,'学习3个单词并复习');assert.equal(s.goals[1].tasks.reduce((n,t)=>n+t.reward,0),500);report.push('单项调整确认后生效，剩余奖励不变');
await click('pauseGoal');await click('confirmModal');s=await read();assert.equal(s.goals[1].status,'paused');await click('cancelGoal');await click('confirmModal');await click('undoGoal');await click('confirmModal');s=await read();assert.equal(s.goals[1].status,'paused');assert.equal(s.quota.undo,1);assert.equal(s.quota.cancel,1);await click('resumeGoal');report.push('暂停、取消、撤回与恢复，次数和名额准确');
await page.locator('#nav [data-page="agent"]').click();await page.locator('#chat-input').fill('记住：我喜欢早晨阅读');await page.locator('#chat-form button').click();await click('memories');const memoryRow=page.locator('.memory').filter({hasText:'我喜欢早晨阅读'});await memoryRow.locator('[data-action="deleteMemory"]').click();await click('confirmModal');s=await read();assert(!s.memories.some(m=>m.text==='我喜欢早晨阅读'));await page.locator('#chat-input').fill('你记得什么偏好');await page.locator('#chat-form button').click();s=await read();assert(!s.messages.at(-1).text.includes('早晨'));await page.screenshot({path:'preview-agent.png'});report.push('日常对话、明确记忆、删除后不再引用');
await click('settings');await click('bindEmail');await page.locator('[name="email"]').fill('demo@example.com');await click('sendCode');await page.locator('[name="code"]').fill('246810');await page.locator('#auth-form button[type="submit"]').click();const bound=(await read()).userId;await click('recover');await click('sendCode');await page.locator('[name="code"]').fill('246810');await page.locator('#auth-form button[type="submit"]').click();assert.equal((await read()).userId,bound);report.push('明确标注的邮箱绑定与恢复演示，用户ID不变');
await click('settings');await page.locator('[data-action="scenario"][data-mode="free"]').click();await click('confirmModal');await click('free');await click('freeStart');await click('freeComplete');s=await read();assert.equal(s.coins,500);assert.equal(s.xp,300);await click('exchange');await click('confirmModal');s=await read();assert.equal(s.cards,1);assert.equal(s.coins,0);report.push('无卡免费行动→金币→任务卡闭环');
await click('settings');await click('offline');await page.locator('#nav [data-page="bag"]').click();await click('exchange');await click('confirmModal');assert.equal((await read()).cards,1);await click('close');await click('settings');await click('offline');report.push('模拟离线阻止资产变更');
for(const width of [360,390,430]){await page.setViewportSize({width,height:800});await page.locator('#nav [data-page="plans"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
assert.deepEqual(errors,[]);report.push('360/390/430宽度无横向溢出；浏览器无未捕获错误');fs.writeFileSync('browser-test-results.json',JSON.stringify({passed:report.length,report,errors},null,2));console.log(report.join('\n'));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
