/* Home-only visual layer, based on the approved P0 home mockup. */
const oldHeader=header,oldNav=nav,oldRender=render;
const homeCrops={avatar:[48,70,118,119],coin:[533,61,48,52],ticket:[752,64,36,45],book:[368,356,61,46],sprout:[54,269,53,56],room:[106,1504,76,66],plans:[330,1504,64,66],agent:[550,1504,73,62],bag:[781,1505,63,62]};
function pixelArt(name){return '<svg class="pixel-art pixel-'+name+'" viewBox="'+homeCrops[name].join(' ')+'" aria-hidden="true"><image href="assets/home-reference.webp" width="941" height="1672"/></svg>'}
function homeLevel(xp){let level=1,remaining=Math.max(0,xp);const cost=l=>l<=5?100:l<=10?150:l<=19?200:l<=30?400:l<=50?600:800;while(level<60&&remaining>=cost(level)){remaining-=cost(level);level++}return{level,remaining:level===60?0:remaining,cost:cost(level)}}
header=function(){if(route==='agent')return agentTop();if(!['room','plans','agent'].includes(route))return oldHeader();const lv=homeLevel(state.xp);return '<section class="room-profile"><div class="room-portrait">'+pixelArt('avatar')+'</div><div class="room-name">旅行者</div>'+btn('⚙','settings','room-settings','aria-label="设置"')+'<div class="room-level">Lv. '+lv.level+'</div><div class="room-xp"><i style="width:'+(lv.level===60?100:lv.remaining/lv.cost*100)+'%"></i></div><div class="room-xp-label">'+(lv.level===60?'已达最高等级':lv.remaining+' / '+lv.cost)+'</div></section><div class="room-assets"><div class="room-asset" aria-label="金币余额">'+pixelArt('coin')+'<b>'+state.coins.toLocaleString()+'</b></div>'+btn(pixelArt('ticket')+'<b>'+state.cards+'</b><span class="room-plus">＋</span>','exchange','room-asset','aria-label="兑换任务卡"')+'</div>'};
nav=function(){if(!['room','plans','agent'].includes(route))return oldNav();return ['room','plans','agent','bag'].map((r,i)=>btn(pixelArt(r)+'<span>'+['房间','计划','Agent','背包'][i]+'</span>','nav',r===route?'active':'','data-page="'+r+'"')).join('')};
room=function(){const ts=todayTasks(),pending=ts.filter(x=>x.t.state!=='done'),selected=pending[0]||ts[0],done=ts.filter(x=>x.t.state==='done').length,p=selected&&M.progress(selected.g);const date=new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'});let body='';
if(selected){const {g,t}=selected,attrs='data-g="'+g.id+'" data-t="'+t.id+'"';body='<div class="room-task-body"><div class="room-task-summary"><div class="room-book">'+pixelArt('book')+'</div><div class="room-task-copy"><h3>'+esc(t.title)+'</h3><p>'+esc(g.title)+' · '+esc(t.stageName||('第 '+(Number(t.stage||0)+1)+' 阶段'))+'</p></div>'+btn(({ready:'待开始',running:'进行中',paused:'已暂停',done:'已完成'})[t.state],'task','room-task-status',attrs)+'</div><div class="room-reward"><span class="exp-icon">EXP</span><span>'+t.reward+' EXP</span>'+pixelArt('coin')+'<span>'+t.reward+' 金币</span></div>'+(pending.length?btn(t.state==='running'?'回到行动':t.state==='paused'?'继续行动':'开始行动','homeStart','room-start',attrs):btn('查看我的计划','plans','room-start'))+(ts.length>1?btn('查看全部 '+ts.length+' 项任务 ›','plans','room-all'):'')+'</div><div class="room-progress">今日 <b>'+done+'/'+ts.length+'</b><span>·</span>阶段 <b>'+p.completedStages+'/'+p.stages+'</b><span>·</span>目标 <button type="button" data-action="goalCountDetails" style="padding:0;border:0;background:none;font:inherit;color:inherit;text-decoration:underline;pointer-events:auto" aria-label="查看大目标统计明细">'+state.goals.filter(x=>x.status==='completed').length+'/'+state.goals.filter(x=>x.status!=='cancelled').length+'</button></div>'}
else body='<div class="room-task-empty">'+referenceArt('calendar')+'<h3>今天暂时没有任务安排</h3><p>'+(state.goals.length?'这不代表你的目标已经全部完成，<br>可以去计划页查看完整安排。':'从一个小小的目标开始，<br>让 Agent 陪你迈出第一步。')+'</p>'+btn('▤ 查看我的计划','plans','room-start')+btn(pixelArt('agent')+'去找 Agent 聊聊','agent','room-chat')+'</div>';
return btn(pixelArt('sprout')+'<span>成长记录</span>','records','room-records')+btn(referenceArt('shop')+'<span>商城</span>','nav','room-records room-shop','data-page="shop"')+'<section class="room-task-panel '+(!selected?'is-empty':'')+'">'+(selected?'<div class="room-task-heading">'+pixelArt('plans')+'<h2>今日任务</h2><time>'+date+'</time></div>':'')+body+'</section>'+btn('今天，从一小步开始。','agent','room-speech','aria-label="和Agent聊天"')+(M.eligible(state)?btn('✧ 免费基础行动 ›','free','room-free'):'')};
render=function(){document.querySelector('#phone').classList.toggle('room-view',['room','plans','agent'].includes(route));document.querySelector('#phone').classList.toggle('plans-open',route==='plans');document.querySelector('#phone').classList.toggle('agent-open',route==='agent');oldRender()};

function referenceArt(kind){const v=kind==='calendar'?'835 245 475 255':'67 734 80 77';return '<svg class="reference-art '+kind+'-art" viewBox="'+v+'" aria-hidden="true"><image href="assets/empty-reference.webp" width="1440" height="2560"/></svg>'}
function shop(){return '<div class="page-heading">'+btn('‹ 返回房间','room','subtle')+'<h1>商城</h1></div><section class="panel"><div class="eyebrow">为下一步，积累一点可能</div><h2>任务卡</h2><div class="shop-ticket">'+pixelArt('ticket')+'</div><p>开启一个新的目标，与 Agent 一起制定计划。</p><div class="summary-list"><div><span>兑换价格</span><b>500 金币 / 张</b></div><div><span>当前金币</span><b>'+state.coins+'</b></div><div><span>已持有任务卡</span><b>'+state.cards+' 张</b></div></div>'+btn('兑换任务卡','exchange','primary wide spaced')+'<p class="caption">兑换后收纳至背包，创建目标时消耗。</p></section><section class="panel"><h3>基础装扮</h3><p class="caption">发型 · 上衣 · 下装</p><p>装扮区域将在商城视觉与交互制作阶段补齐。</p></section>'}
render();



