(()=>{
const panel=document.getElementById('launch'),bar=panel.querySelector('[role=progressbar]'),fill=panel.querySelector('.launch-fill'),value=panel.querySelector('output'),status=panel.querySelector('.launch-status'),retry=panel.querySelector('button');
const assets=['assets/launch-reference.webp','assets/room.webp','assets/blink-open.webp','assets/blink-half.webp','assets/blink-closed.webp','assets/home-reference.webp','assets/empty-reference.webp','assets/wardrobe/avatar-original.webp',...['room','plans','agent','bag'].map(n=>'assets/nav-'+n+'.webp')];
let running=false,ready=false,entering=false,autoLeft=2;
function progress(n){bar.setAttribute('aria-valuenow',n);fill.style.width=n+'%';value.textContent=n+'%'}
function load(src){return new Promise((resolve,reject)=>{const im=new Image();const timeout=setTimeout(()=>reject(new Error('加载超时')),30000);im.onload=()=>{clearTimeout(timeout);(im.decode?im.decode():Promise.resolve()).then(resolve,reject)};im.onerror=()=>{clearTimeout(timeout);reject(new Error('资源加载失败'))};im.src=src})}
async function loadWithRetry(src){try{return await load(src)}catch(e){await new Promise(r=>setTimeout(r,800));return load(src)}}
async function run(){if(running)return;running=true;retry.hidden=true;progress(0);status.textContent='正在加载房间与角色…';const total=assets.length+2;let done=0;const finish=()=>progress(Math.floor(++done/total*100));try{if(!navigator.onLine)throw new Error('请连接网络后重试');await Promise.all(assets.map(async src=>{await loadWithRetry(src);finish()}));await document.fonts.ready;finish();if(typeof state==='undefined'||!state.userId)throw new Error('初始化未完成，请刷新重试');if(!save())throw new Error('无法保存进度，请检查浏览器存储空间');route='room';render();finish();status.textContent='点击屏幕进入游戏';ready=true;panel.tabIndex=0;panel.focus();}catch(e){if(autoLeft-->0&&navigator.onLine){status.textContent='网络较慢，正在自动重试…';setTimeout(run,1500);return}status.textContent=e.message+'（已自动重试，请检查网络）';retry.hidden=false}finally{running=false}}
async function enter(){if(!ready||entering)return;entering=true;panel.classList.add('leaving');await new Promise(r=>setTimeout(r,450));panel.hidden=true;document.getElementById('phone').classList.remove('launch-active');document.dispatchEvent(new Event('myself-entered'));}
panel.addEventListener('click',e=>{if(e.target===retry)return;enter()});panel.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();enter()}});retry.addEventListener('click',run);document.getElementById('phone').classList.add('launch-active');run();
})();

