(()=>{
const panel=document.getElementById('launch'),bar=panel.querySelector('[role=progressbar]'),fill=panel.querySelector('.launch-fill'),value=panel.querySelector('output'),status=panel.querySelector('.launch-status'),retry=panel.querySelector('button');
const manifest=window.MYSELF_STARTUP_ASSETS;
const info=document.createElement('p');info.className='launch-transfer';status.after(info);
let running=false,ready=false,entering=false,received=new Map(),done=new Set(),runBytes=0,lastBytes=0,lastTime=0,speed=0,autoAttempts=0,autoTimer,launchBlob;
const total=()=>manifest.reduce((n,a)=>n+a.bytes,0),mb=n=>(n/1048576).toFixed(2)+' MB';
function progress(n){bar.setAttribute('aria-valuenow',n);fill.style.width=n+'%';value.textContent=n+'%'}
function update(){const bytes=manifest.reduce((n,a)=>n+Math.min(received.get(a.src)||0,a.bytes),0);if(!ready)progress(Math.min(95,Math.floor(bytes/total()*95)));info.textContent=mb(bytes)+' / '+mb(total())+' · '+(running?(speed/1024).toFixed(0)+' KB/s':'已暂停')+'（资源读取）'}
async function load(a){const controller=new AbortController();let timer;const arm=()=>{clearTimeout(timer);timer=setTimeout(()=>controller.abort(),45000)};received.set(a.src,0);arm();try{const r=await fetch(a.src,{signal:controller.signal,cache:autoAttempts?'reload':'force-cache'});if(!r.ok)throw Error('HTTP '+r.status);const chunks=[];let bytes=0;if(r.body?.getReader){const reader=r.body.getReader();while(true){const v=await reader.read();if(v.done)break;chunks.push(v.value);bytes+=v.value.byteLength;runBytes+=v.value.byteLength;received.set(a.src,bytes);arm();update()}}else{const data=await r.arrayBuffer();chunks.push(data);bytes=data.byteLength;runBytes+=bytes;received.set(a.src,bytes)}clearTimeout(timer);if(!bytes)throw Error('资源为空');const blob=new Blob(chunks,{type:r.headers.get('content-type')||'image/png'}),url=URL.createObjectURL(blob);try{await new Promise((resolve,reject)=>{const im=new Image();const t=setTimeout(()=>reject(Error('图片读取超时')),15000);im.onload=()=>{clearTimeout(t);resolve()};im.onerror=()=>{clearTimeout(t);reject(Error('图片无法解码'))};im.src=url});if(a.src.includes('launch-reference')){if(launchBlob)URL.revokeObjectURL(launchBlob);launchBlob=url;panel.querySelector('img').src=url}}finally{if(url!==launchBlob)URL.revokeObjectURL(url)}received.set(a.src,a.bytes);done.add(a.src);update()}finally{clearTimeout(timer);controller.abort()}}
async function run(){if(running||ready)return;clearTimeout(autoTimer);running=true;retry.hidden=true;status.textContent='正在加载房间与角色…';lastTime=performance.now();lastBytes=runBytes;const ticker=setInterval(()=>{const now=performance.now();speed=(runBytes-lastBytes)/((now-lastTime)/1000);lastBytes=runBytes;lastTime=now;update()},500);try{if(!navigator.onLine){const e=Error('当前离线，联网后将自动继续');e.offline=true;throw e;}const queue=manifest.filter(a=>!done.has(a.src)),failures=[];await Promise.all([0,1].map(async()=>{while(queue.length){const a=queue.shift();try{await load(a)}catch(e){failures.push({asset:a,error:e});received.set(a.src,0)}}}));if(failures.length){const e=Error(failures.some(f=>f.error.message==='HTTP 404')?'配套图片尚未发布完整':'网络不稳定，部分图片尚未加载完成');e.retryable=true;throw e;}status.textContent='正在恢复游戏进度…';if(document.fonts?.ready)await Promise.race([document.fonts.ready,new Promise(r=>setTimeout(r,3000))]);if(typeof state==='undefined'||!state.userId)throw Error('初始化未完成，请刷新重试');if(!save())throw Error('无法保存进度，请检查浏览器存储空间');route='room';render();ready=true;progress(100);status.textContent='点击屏幕进入游戏';info.textContent=mb(total())+' / '+mb(total())+' · 已就绪';panel.tabIndex=0;panel.focus()}catch(e){status.textContent=e.message;if(e.retryable&&autoAttempts<5){const delay=[2000,4000,8000,15000,30000][autoAttempts++];status.textContent+='，'+delay/1000+'秒后自动重试';autoTimer=setTimeout(run,delay)}else if(!e.offline){retry.hidden=false;retry.textContent='重新检查';if(e.retryable)status.textContent+='。请检查图片上传或网络连接。'}}finally{running=false;clearInterval(ticker);if(!ready)update()}}
async function enter(){if(!ready||entering)return;entering=true;panel.classList.add('leaving');await new Promise(r=>setTimeout(r,450));panel.hidden=true;document.getElementById('phone').classList.remove('launch-active');document.dispatchEvent(new Event('myself-entered'))}
panel.addEventListener('click',e=>{if(e.target!==retry)enter()});panel.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();enter()}});retry.addEventListener('click',()=>{autoAttempts=0;run()});window.addEventListener('online',()=>{autoAttempts=0;run()});document.getElementById('phone').classList.add('launch-active');run();
})();

