/* Review UI: generation message -> chat card -> centred stage overview. */
let reviewOpen=false,reviewFocus=null;
function planStages(d){const days=Number(d.days),count=Math.min(3,days),names=['开始行动','稳定练习','巩固与回顾'];let offset=0;return Array.from({length:count},(_,i)=>{const n=Math.floor(days/count)+(i<days%count?1:0),tasks=Array.from({length:n},()=>({title:d.action,date:M.plusDay(d.date||M.day(),offset++),difficulty:'低',reward:100,stage:i,stageName:names[i]}));return {name:names[i],tasks}})}
function beginPlanGeneration(f){f.mode='generating';f.data.date=f.data.date||M.day();f.draftId=f.draftId||M.id();say('正在帮你整理「'+esc(f.data.title||'这次目标')+'」的安排，马上好…');setTimeout(()=>finishPlanGeneration(f),1000)}
function finishPlanGeneration(f){if(flow()!==f||f.mode!=='generating')return;f.mode='review';say('我已经整理好啦，你觉得这样如何？有要修改的地方可以和我说哦。');if(route==='agent')refreshChat()}
const beforeReviewCard=conversationCard;
conversationCard=function(){const f=flow();if(f.mode==='generating')return '<div class="plan-generating" role="status">✦ 正在整理整体安排…</div>';if(f.mode==='review')return '<button class="plan-chat-card" data-action="openPlanReview">'+pixelArt('plans')+'<span><b>'+esc(f.data.title)+'</b><small>'+f.data.days+' 天 · '+planStages(f.data).length+' 个阶段 · 查看完整安排</small></span><strong>›</strong></button>';return beforeReviewCard()};
function showPlanReview(){if(flow().mode!=='review')return;reviewOpen=true;reviewFocus=document.activeElement;const f=flow(),d=f.data,stages=planStages(d),tasks=stages.flatMap(s=>s.tasks);let root=document.getElementById('plan-review-root');if(!root){root=document.createElement('div');root.id='plan-review-root';document.getElementById('phone').appendChild(root)}root.innerHTML='<div class="plan-review-backdrop"><section class="plan-review-dialog" role="dialog" aria-modal="true" aria-labelledby="review-title"><header><h2 id="review-title">▤ 计划待确认</h2>'+btn('×','closePlanReview','review-close','aria-label="关闭计划确认表"')+'</header><div class="plan-review-scroll"><section class="review-summary"><h3>'+esc(d.title)+'</h3><p>'+esc(d.action)+'</p><small>◷ '+esc(d.time)+' · '+esc(d.foundation)+'</small><p class="review-range">整体安排：'+tasks[0].date+' — '+tasks.at(-1).date+'<br>'+d.days+' 天 · '+stages.length+' 个阶段 · '+tasks.length+' 项每日任务</p></section>'+stages.map((s,i)=>'<details class="review-stage" '+(i===0?'open':'')+'><summary><span>第'+(i+1)+'阶段：'+esc(s.name)+'<small>'+s.tasks.length+' 项任务 · '+s.tasks[0].date+' — '+s.tasks.at(-1).date+'</small></span><b>⌄</b></summary><div class="review-daily">'+s.tasks.map(t=>'<article><div class="review-date"><small>'+Number(t.date.slice(5,7))+'月</small><b>'+Number(t.date.slice(8))+'日</b></div><div><h4>'+esc(t.title)+'</h4><span class="review-difficulty">'+esc(t.difficulty)+'难度</span><p><span>EXP</span> '+t.reward+' EXP　🪙 '+t.reward+' 金币</p></div></article>').join('')+'</div></details>').join('')+'<section class="review-total"><b>基础奖励合计</b><span>'+tasks.reduce((sum,t)=>sum+t.reward,0)+' EXP · '+tasks.reduce((sum,t)=>sum+t.reward,0)+' 金币</span></section><section class="review-cost"><b>创建消耗 1 张任务卡</b><p>当前任务卡 '+state.cards+' 张 · 名额 '+M.slots(state)+'/5</p></section><p class="review-note">确认成功后扣卡，修改方案不扣卡。<br>AI 方案请先核对；奖励按系统难度规则计算。</p></div><footer>'+btn('修改方案','editPlanReview')+btn('确认创建','confirmPlanReview','primary')+'</footer></section></div>';root.querySelector('.review-close').focus({preventScroll:true});document.querySelector('.agent-window').inert=true;document.querySelector('#nav').inert=true;document.querySelector('#top').inert=true}
function closePlanReview(){document.getElementById('plan-review-root')?.remove();reviewOpen=false;document.querySelector('.agent-window')?.removeAttribute('inert');document.querySelector('#nav').inert=false;document.querySelector('#top').inert=false;reviewFocus?.isConnected&&reviewFocus.focus({preventScroll:true})}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='openPlanReview')showPlanReview();if(a==='closePlanReview')closePlanReview();if(a==='editPlanReview'){closePlanReview();flow().mode='clarify';flow().pending='action';say('你想改哪一部分？说说你的想法，我们一起调整。');refreshChat();document.getElementById('chat-input')?.focus()}if(a==='confirmPlanReview')showCreateConfirmation();if(a==='backToPlanReview')showPlanReview();if(a==='commitPlanCreation')commitPlanCreation();if(a==='finishPlanCreation'){closePlanReview();refreshChat()}});
let createBusy=false;
function showCreateConfirmation(){if(flow().mode!=='review')return;const dialog=document.querySelector('.plan-review-dialog');if(!dialog)return;dialog.innerHTML='<header><h2 id="review-title">确认创建这个目标？</h2></header><div class="plan-review-scroll"><section class="review-summary"><h3>'+esc(flow().data.title)+'</h3><p>将消耗 1 张任务卡，并占用 1 个目标名额。</p><p>当前任务卡：'+state.cards+' 张 · 当前名额：'+M.slots(state)+'/5</p><p class="caption">确认成功后才会扣卡；返回不会改变方案。</p></section></div><footer>'+btn('我再想想','backToPlanReview')+btn('确认创建','commitPlanCreation','primary')+'</footer>';dialog.querySelector('button').focus({preventScroll:true});}
function commitPlanCreation(){const f=flow();if(createBusy||f.mode!=='review')return;createBusy=true;try{const d=f.data,tasks=planStages(d).flatMap(s=>s.tasks);const r=transact('create',{title:d.title,draftId:f.draftId,context:[d.foundation,d.time,d.obstacle].join('；'),tasks},f.draftId);if(!r)return;chatContext=r.result.goalId;state.agentFlow={mode:'chat',data:{}};say('行动创建成功，已消耗1张任务卡。完整阶段与每日安排已保存到计划中。');const dialog=document.querySelector('.plan-review-dialog');dialog.innerHTML='<header><h2 id="review-title">创建成功</h2></header><div class="plan-review-scroll"><section class="review-summary"><h3>'+esc(d.title)+'</h3><p>已消耗 1 张任务卡，计划已保存。</p><p>剩余任务卡：'+state.cards+' 张 · 当前名额：'+M.slots(state)+'/5</p></section></div><footer>'+btn('好的','finishPlanCreation','primary')+'</footer>';dialog.querySelector('button').focus({preventScroll:true});}finally{createBusy=false;}}

document.addEventListener('keydown',e=>{if(!reviewOpen)return;if(e.key==='Escape'){e.preventDefault();closePlanReview()}if(e.key==='Tab'){const els=[...document.querySelectorAll('.plan-review-dialog button,.plan-review-dialog summary')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
if(flow().mode==='generating'){flow().mode='chat';save()}
render();