const WC=window.WardrobeCatalog;
let wearDraft=null,wearCategory='head',wearTool=false,wearSelected=null,wearPurchase=null;
const savedWear=()=>({...WC.defaults,...state.outfit});
const wearOwned=id=>Object.values(WC.defaults).includes(id)||(state.ownedClothes||[]).includes(id);
const wearItem=id=>WC.items.find(i=>i.id===id);
function wearCrop(file,box,size,x=0,y=0,w=100,h=100){return `<svg x="${x}" y="${y}" width="${w}" height="${h}" viewBox="${box.join(' ')}" preserveAspectRatio="xMidYMid meet"><image href="${file}" width="${size[0]}" height="${size[1]}"/></svg>`}
function wearThumb(item,slot=wearCategory){return `<svg viewBox="0 0 100 100" aria-hidden="true">${item?wearCrop(item.file,item.bbox,item.size):wearCrop('assets/wardrobe/base.png',slot==='top'?[190,610,650,510]:slot==='bottom'?[275,1050,480,480]:[180,60,660,570],[1024,1536])}</svg>`}
function wearCharacter(outfit=savedWear(),portrait=false){const base='assets/wardrobe/base.png',size=[1024,1536],top=wearItem(outfit.top),bottom=wearItem(outfit.bottom),head=wearItem(outfit.head);return `<svg class="wear-character" viewBox="${portrait?'25 0 350 345':'0 0 400 660'}" role="img" aria-label="当前角色装扮" data-outfit="${esc(JSON.stringify(outfit))}">${bottom?wearCrop(bottom.file,bottom.bbox,bottom.size,93,419,218,229):wearCrop(base,[275,1050,480,480],size,93,419,218,229)}${top?wearCrop(top.file,top.bbox,top.size,54,252,292,265):wearCrop(base,[190,610,650,510],size,54,252,292,265)}${wearCrop(base,[175,55,675,580],size,42,12,316,272)}${head?wearCrop(head.file,head.bbox,head.size,head.hat?38:108,head.hat?0:54,head.hat?324:52,head.hat?194:48):''}</svg>`}
const wearOldArt=pixelArt;
// 【人物还原 2026-10-05】头像恢复为10-02原版形象（avatar-original.png），不再用base.png裁切。
pixelArt=function(name){if(name==='avatar')return '<svg class="wear-character" viewBox="0 0 116 145" role="img" aria-label="旅行者头像"><image href="assets/wardrobe/avatar-original.png" width="116" height="145"/></svg>';if(name==='ticket')return '<svg class="pixel-art pixel-ticket" viewBox="365 449 101 126" aria-hidden="true"><image href="assets/wardrobe/ticket-reference.png" width="941" height="1672"/></svg>';return wearOldArt(name)};
// 【人物还原 2026-10-05】房间页恢复原版背景图（assets/room.png 内含原版坐姿小人），不再叠加纸娃娃。
const wearOldRoom=room;room=function(){return wearOldRoom()};
const wearOldHeader=header,wearOldNav=nav,wearOldRender=render,wearOldGo=go;
header=function(){if(!['bag','shop'].includes(route))return wearOldHeader();return `<div class="wear-header">${btn('‹','room','wear-back','aria-label="返回房间"')}<h1>${route==='bag'?'背包':'商城'}</h1><div class="wear-money">${pixelArt('coin')}<b>${state.coins}</b></div>${btn(pixelArt('ticket')+`<b>${state.cards}</b> ＋`,'exchange','wear-money','aria-label="兑换任务卡"')}</div>`};
nav=function(){if(!['bag','shop'].includes(route))return wearOldNav();return ['room','plans','agent','bag'].map((r,i)=>btn(pixelArt(r)+`<span>${['房间','计划','Agent','背包'][i]}</span>`,'nav',r==='bag'?'active':'',`data-page="${r}"`)).join('')};
go=function(r){if(['bag','shop'].includes(route)&&!['bag','shop'].includes(r)&&wearDraft&&JSON.stringify(wearDraft)!==JSON.stringify(savedWear())){openModal('穿搭尚未保存','<p>离开后会恢复上次保存的穿搭，已购买的物品仍在背包里。</p>',()=>{wearDraft=null;closeModal();wearOldGo(r)},'放弃试穿并离开');return}if(['bag','shop'].includes(r)&&!wearDraft)wearDraft=savedWear();wearOldGo(r)};
render=function(){document.querySelector('#phone').classList.toggle('wardrobe-view',['bag','shop'].includes(route));document.querySelector('#phone').classList.toggle('outfit-room',false);wearOldRender()};
function wearPage(isShop){wearDraft=wearDraft||savedWear();const selected=wearItem(wearSelected)||wearItem(wearDraft[wearCategory]),pending=WC.slots.map(s=>wearDraft[s]).filter(id=>!wearOwned(id)),items=WC.items.filter(i=>i.slot===wearCategory);return `<div class="wear-stage"><div class="wear-avatar">${wearCharacter(wearDraft)}</div><section class="wear-preview"><h2>${isShop?'试穿预览':'当前装扮'}</h2><div class="wear-slots">${WC.slots.map((s,i)=>btn(wearThumb(wearItem(wearDraft[s]),s)+`<small>${['头饰','上装','下装'][i]}</small>`,'wearSlot',wearCategory===s?'chosen':'',`data-slot="${s}"`)).join('')}</div><b class="wear-item-name">${selected?esc(selected.name):'初始装扮'}</b><p>${selected?(wearOwned(selected.id)?'已拥有':selected.price+' 金币'):'免费 · 已拥有'}</p>${btn('恢复原装','wearReset','wear-reset')}${btn(pending.length?'购买并保存':'保存穿搭','wearSave','primary')}</section></div><section class="wear-inventory"><div class="wear-main-tabs">${btn(isShop?'服饰':'装备','wearEquipment',!wearTool?'active':'')}${btn('道具','wearTools',wearTool?'active':'')}${btn(isShop?'我的背包 ›':'逛逛商城 ›','wearSwitch','')}</div>${wearTool?`<div class="wear-card-detail"><div class="wear-card-art">${pixelArt('ticket')}</div><h2>任务卡 <small>× ${state.cards}</small></h2><p>每创建一个新目标消耗1张。</p><p>当前名额 ${M.slots(state)} / 5</p>${btn('500 金币兑换1张','exchange','primary')}${btn('去创建目标','agent','')}<p class="caption">兑换后加入背包，创建目标时才消耗。</p></div>`:`<div class="wear-categories">${WC.slots.map((s,i)=>btn(['头饰','上装','下装'][i],'wearSlot',wearCategory===s?'active':'',`data-slot="${s}"`)).join('')}</div><div class="wear-grid ${isShop?'shop-grid':''}">${[null,...items].map(item=>{const id=item?.id||WC.defaults[wearCategory],owned=wearOwned(id),chosen=wearDraft[wearCategory]===id;return btn(wearThumb(item)+`<strong>${item?esc(item.name):wearCategory==='head'?'不戴头饰':'初始'+(wearCategory==='top'?'上装':'下装')}</strong><small>${chosen?'✓ 试穿中':owned?'已拥有':'◈ 300 金币'}</small>`,'wearTry',(chosen?'chosen ':'')+(!owned?'unowned':''),`data-id="${id}"`)}).join('')}</div><p class="wear-count">已拥有 ${(state.ownedClothes||[]).length} / ${WC.items.length} 件 · 点击装扮试穿</p>`}</section>`}
bag=()=>wearPage(false);shop=()=>wearPage(true);
function wearSave(){const pending=WC.slots.map(s=>wearItem(wearDraft[s])).filter(i=>i&&!wearOwned(i.id));if(pending.length){wearPurchase={items:pending,selected:new Set(pending.map(i=>i.id)),preview:{...wearDraft},rid:M.id()};wearPurchaseModal();return}if(transact('saveOutfit',{outfit:wearDraft})){wearDraft=savedWear();render();toast('穿搭已保存，房间角色与头像已更新。')}}
function wearPurchaseModal(){const p=wearPurchase;openModal('购买试穿装扮',`<div class="wear-checkout"><div class="wear-single-preview">${wearCharacter(p.preview)}</div><p>未拥有的装扮需先购买才能保存。可勾选购买，点击预览查看单件效果。</p>${p.items.map(i=>`<div class="wear-buy-row"><input type="checkbox" aria-label="购买${esc(i.name)}" data-wear-buy="${i.id}" ${p.selected.has(i.id)?'checked':''}>${wearThumb(i)}<div><b>${esc(i.name)}</b><small>${i.price} 金币</small></div>${btn('预览','wearSingle','',`data-id="${i.id}"`)}</div>`).join('')}<p class="wear-buy-total">合计 ${p.items.filter(i=>p.selected.has(i.id)).reduce((n,i)=>n+i.price,0)} 金币 · 余额 ${state.coins}</p></div>`,()=>{const r=transact('purchaseClothes',{ids:[...p.selected]},p.rid);if(!r)return;closeModal();render();if(WC.slots.some(s=>!wearOwned(wearDraft[s])))toast('所选装扮已加入背包，其余试穿装扮尚未购买。');else wearSave()},'购买所选'+(p.items.every(i=>p.selected.has(i.id))?'并保存':''))}
exchange=function(){const rid=M.id();openModal('任务卡快捷兑换',`<div class="wear-card-detail"><div class="wear-card-art">${pixelArt('ticket')}</div><h2>任务卡 × 1</h2><p>每创建一个新目标消耗1张。</p><p>当前持有 ${state.cards} 张 · 名额 ${M.slots(state)} / 5</p><div class="wear-exchange-summary">−500 金币 → ＋1 张任务卡</div><p>金币余额 ${state.coins}${state.coins<500?' · 还差 '+(500-state.coins)+' 金币':''}</p></div>`,()=>{if(!transact('exchange',{},rid))return;closeModal();render();openModal('兑换成功 · 已加入背包',`<div class="wear-card-detail"><div class="wear-card-art">${pixelArt('ticket')}</div><h2>任务卡 × ${state.cards}</h2><p>本次 −500 金币 · ＋1 张任务卡</p><p>金币余额 ${state.coins}</p></div>`,()=>{closeModal();wearTool=true;go('bag')},'查看背包')},'确认兑换')};
document.addEventListener('change',e=>{const id=e.target.dataset.wearBuy;if(!id||!wearPurchase)return;e.target.checked?wearPurchase.selected.add(id):wearPurchase.selected.delete(id);wearPurchaseModal()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||!b.dataset.action.startsWith('wear'))return;e.preventDefault();e.stopImmediatePropagation();const d=b.dataset;switch(d.action){case'wearSlot':wearCategory=d.slot;wearTool=false;wearSelected=wearDraft[wearCategory];break;case'wearTry':wearDraft[wearCategory]=d.id;wearSelected=d.id;track('outfit_preview',{itemId:d.id});break;case'wearReset':wearDraft=savedWear();wearSelected=null;break;case'wearSave':wearSave();return;case'wearTools':wearTool=true;break;case'wearEquipment':wearTool=false;break;case'wearSwitch':go(route==='shop'?'bag':'shop');return;case'wearSingle':{const item=wearItem(d.id);wearPurchase.preview={...WC.defaults,[item.slot]:item.id};wearPurchaseModal();return}}render()},true);
render();
